# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Sam/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12196-LAPTOP-ER8O0O9K/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcu250-figd2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.cache/wt [current_project]
set_property parent.project_path D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:au250:part0:1.2 [current_project]
set_property ip_output_repo d:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/defines_pkg.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/RAT.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/alu.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/branch.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/decode_controller.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/decode_stage.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/dispatch_logic.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/dispatch_stage.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/execution_stage.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/fetch_stage.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/free_pool.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/icache.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/imm_gen.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/issue_arbiter.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/lsu.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/pc_counter.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/pip_if.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/priority_decoder.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/reg_file.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/rename_stage.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/rob.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/rs.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/skid_buffer_pipe.sv
  D:/UCLA_Master/ECE_189/OoO_RISC_V_CPU_DESIGN/OoO_RISC_V_CPU_DESIGN.srcs/sources_1/new/top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcu250-figd2104-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
